### ISSUE TITLE
How about the results if i don't use the text-image function?

### ISSUE THREAD

**Issue by jianglai3303** [hanzhanggit/StackGAN#10]
Hi, guys. I'm really curious about whether this network can be applied to generate images merely based on image dataset.

And i have deleted the text-encoding module from the code, train the model intimately.The result of stageII is not so satisfactory.

Can anyone give me some advices? Thanks

**Comment by taoxugit** [comment]
Hi, 

Our experimental results show that the conditioning augmentation proposed in the paper is very important for generating high-resolution images in stage-II. Since you have deleted the text-encoding module, it means that there is no conditioning augmentation in your stage-II GAN. That might be the reason your stage-II result is not so satisfactory.

Here are some suggestions to make your model better:
(1) Try new hyper-parameters and network structures for your unconditional version of StackGAN. Our new results show that if you add one extra layer (e.g., 64x64x(gf//2)) before the output layer (64x64x3) of stage-I GAN, you can get better stageI results, thus you might get better stageII results as well. 
(2) In stage-II GAN, you might try to input the same or augmented z vector at where the original text conditioning augmentation vector c is inputed, because our paper also demonstrates that it is useful to input text information again in stage-II GAN to encourage it to add more details to the high-resolution image and correct defects in the low-resolution input image.
